"""
Use this script to export the split XML stored in the SQLITE database file 
generated by dump_splitter.py, into a .xml flatfile that is ready to import 
into a MediaWiki instance. 

Config:
 - INPUT_SPLIT_DUMP: The filepath of the SQLITE database file (generated by dump_splitter.py)
 - OUTPUT_DIRECTORY: The file directory of the output XML file
 - FILENAME_PREFIX: The filename of the output XML file will be named after this config variable. 
                    Multiple XML files may be generated. In this case the files will be numbered "_1", "_2", etc.
 - MAX_NUMBER_OF_PAGES_PER_XML: Set the maximum limit of number of pages to export per XML file, 
                                e.g. you can set the script to export the wikipages into several XML files with a 
                                     maximum of 100 pages per file.

 - ONLY_IN_NAMESPACES: Only for these namespaces, e.g. 0 = Main article.
                       Leave empty if not filtering for namespace.
 - ONLY_PAGEIDS: Only for the following page IDs. 
                 Leave empty if not filtering for page ID.
 - EXCLUDE_PAGEIDS: Exclude these page IDs.
                    Leave empty if not filtering for page ID.
 - EXPORT_REDIRECTS:  Set to 0 if you want to export non-redirects
                      Set to 1 if you want to export redirects only
                      Set to 2 if you want to export all pages, including redirects

 - GET_NUMBER_OF_ITEMS_PER_DB_REQ: Adjust based on your computer's RAM
 - SITEINFO_XML: Adjust based on your wiki's siteinfo
"""

import sqlite3

INPUT_SPLIT_DUMP = "C:\\Users\\path\\to\\file.db"
OUTPUT_DIRECTORY = "C:\\Users\\folder\\path\\"

FILENAME_PREFIX = "EXPORTED_XML"

MAX_NUMBER_OF_PAGES_PER_XML = 1000

ONLY_IN_NAMESPACES = [0]
ONLY_PAGEIDS = []
EXCLUDE_PAGEIDS = []
EXPORT_REDIRECTS = 2

GET_NUMBER_OF_ITEMS_PER_DB_REQ = 1000

SITEINFO_XML = """<siteinfo>
    <sitename>Vocaloid Lyrics Wiki</sitename>
    <dbname>vocaloidlyrics</dbname>
    <base>https://vocaloidlyrics.fandom.com/wiki/Vocaloid_Lyrics_Wiki</base>
    <generator>MediaWiki 1.43.0</generator>
    <case>first-letter</case>
    <namespaces>
      <namespace key="-2" case="first-letter">Media</namespace>
      <namespace key="-1" case="first-letter">Special</namespace>
      <namespace key="0" case="first-letter" />
      <namespace key="1" case="first-letter">Talk</namespace>
      <namespace key="2" case="first-letter">User</namespace>
      <namespace key="3" case="first-letter">User talk</namespace>
      <namespace key="4" case="first-letter">Vocaloid Lyrics Wiki</namespace>
      <namespace key="5" case="first-letter">Vocaloid Lyrics Wiki talk</namespace>
      <namespace key="6" case="first-letter">File</namespace>
      <namespace key="7" case="first-letter">File talk</namespace>
      <namespace key="8" case="first-letter">MediaWiki</namespace>
      <namespace key="9" case="first-letter">MediaWiki talk</namespace>
      <namespace key="10" case="first-letter">Template</namespace>
      <namespace key="11" case="first-letter">Template talk</namespace>
      <namespace key="12" case="first-letter">Help</namespace>
      <namespace key="13" case="first-letter">Help talk</namespace>
      <namespace key="14" case="first-letter">Category</namespace>
      <namespace key="15" case="first-letter">Category talk</namespace>
      <namespace key="110" case="first-letter">Forum</namespace>
      <namespace key="111" case="first-letter">Forum talk</namespace>
      <namespace key="420" case="first-letter">GeoJson</namespace>
      <namespace key="421" case="first-letter">GeoJson talk</namespace>
      <namespace key="500" case="first-letter">User blog</namespace>
      <namespace key="501" case="first-letter">User blog comment</namespace>
      <namespace key="502" case="first-letter">Blog</namespace>
      <namespace key="503" case="first-letter">Blog talk</namespace>
      <namespace key="828" case="first-letter">Module</namespace>
      <namespace key="829" case="first-letter">Module talk</namespace>
      <namespace key="1200" case="first-letter">Message Wall</namespace>
      <namespace key="1201" case="first-letter">Thread</namespace>
      <namespace key="1202" case="first-letter">Message Wall Greeting</namespace>
      <namespace key="2000" case="first-letter">Board</namespace>
      <namespace key="2001" case="first-letter">Board Thread</namespace>
      <namespace key="2002" case="first-letter">Topic</namespace>
      <namespace key="2900" case="first-letter">Map</namespace>
      <namespace key="2901" case="first-letter">Map talk</namespace>
    </namespaces>
  </siteinfo>"""

# ==============================================
# === DON'T CHANGE ANYTHING BEYOND THIS LINE ===
# ==============================================

def generate_sql_query(for_count: bool, limit: int, offset: int) -> str:
  query = f"SELECT {"COUNT(w.id)" if for_count else "w.id, w.contents"} FROM Wikipages w\n"
  where_clauses = []
  if len(ONLY_IN_NAMESPACES) > 0:
    where_clauses.append(f"w.ns IN ({','.join(map(lambda x: str(x), ONLY_IN_NAMESPACES))})")
  if len(ONLY_PAGEIDS) > 0:
    where_clauses.append(f"w.id IN ({','.join(map(lambda x: str(x), ONLY_PAGEIDS))})")
  if len(EXCLUDE_PAGEIDS) > 0:
    where_clauses.append(f"w.id NOT IN ({','.join(map(lambda x: str(x), EXCLUDE_PAGEIDS))})")
  if EXPORT_REDIRECTS == 0:
    where_clauses.append(f"w.redirect_to IS NULL")
  if EXPORT_REDIRECTS == 1:
    where_clauses.append(f"w.redirect_to IS NOT NULL")
  
  if len(where_clauses) > 0:
    query += "WHERE " + " AND ".join(where_clauses) + "\n"
  
  if not for_count:
    query += f"LIMIT {limit} OFFSET {offset}"

  query += ";"

  return query

def port_to_split_xml():
  db_conn = sqlite3.connect(INPUT_SPLIT_DUMP)
  db_cursor = db_conn.cursor()
  query = generate_sql_query(True, 0, 0)
  print(f"Executing query:\n{query}")
  num_items = db_cursor.execute(query).fetchone()[0]
  print(f"Found {num_items} items")

  num_text_files = num_items // MAX_NUMBER_OF_PAGES_PER_XML
  if (num_items % MAX_NUMBER_OF_PAGES_PER_XML > 0):
    num_text_files += 1

  for n_txtdump in range(num_text_files):
    filename = f"{FILENAME_PREFIX}-{n_txtdump+1}.xml"
    with open(f"{OUTPUT_DIRECTORY}{filename}", 'w', encoding='UTF-8') as f:
      f.write(f"""<mediawiki xmlns="http://www.mediawiki.org/xml/export-0.11/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mediawiki.org/xml/export-0.11/ http://www.mediawiki.org/xml/export-0.11.xsd" version="0.11" xml:lang="en">
  {SITEINFO_XML}\n  """)
      for n_dbreq in range(MAX_NUMBER_OF_PAGES_PER_XML // GET_NUMBER_OF_ITEMS_PER_DB_REQ):
        query = generate_sql_query(
          False, 
          GET_NUMBER_OF_ITEMS_PER_DB_REQ, 
          n_txtdump * MAX_NUMBER_OF_PAGES_PER_XML + n_dbreq * GET_NUMBER_OF_ITEMS_PER_DB_REQ
        )
        items = db_cursor.execute(query).fetchall()
        for _, contents in items:
          f.write(contents)
      f.write("</mediawiki>\n")
    print(f"Finished writing {filename}")

  db_conn.close()

if __name__ == "__main__":
  port_to_split_xml()
