"""
Use this script to export the split XML stored in the SQLITE database file 
generated by dump_splitter.py, into a .xml flatfile that is ready to import 
into a MediaWiki instance. 
"""

import sqlite3
import re
from config import logger

from typing import List, Literal

def export_xml(
    sql_db_path: str, 
    output_directory: str, 
    root_xml_head: str,
    siteinfo_xml: str,
    exported_filename_prefix: str = "EXPORTED_XML_DUMP_", 
    num_pages_per_file: int = 1000,
    num_items_to_fetch_from_db: int = 200,
    include_namespaces: List[int] = [],
    include_pageids: List[int] = [],
    exclude_namespaces: List[int] = [],
    exclude_pageids: List[int] = [],
    export: Literal["only_non_redirects", "only_redirects", "all"] = "all"
  ):
  """
    Exports an XML dump that has been partitioned into a SQLITE database into several XML files.
    This is useful if you have a very large dump that you'd like to split down into smaller 
    chunks.

    Parameters:
      sql_db_path (str):
        Filepath of SQLITE database
      output_directory (str):
        Output directory of the exported XML files
      root_xml_head (str):
        The string representation of the head tag of the root element of the XML. This should 
        be something like: `<mediawiki xmlns="http://www.mediawiki.org/xml/export-0.11/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mediawiki.org/xml/export-0.11/ http://www.mediawiki.org/xml/export-0.11.xsd" version="0.11" xml:lang="en">`
      siteinfo_xml (str):
        The string representation of the `<siteinfo>` XML node in the MediaWiki dump. This node 
        typically maps the namespace IDs and canonical names.
      exported_filename_prefix (str):
        Prefix of the filename of the exported XML files, e.g. a prefix of "foo_" will name 
        the files "foo_1.xml", etc.
      num_pages_per_file (int):
        Number of wikipages to export per exported XML dump.
      num_items_to_fetch_from_db (int):
        Number of items to fetch from the database at a time.
      include_namespaces (List[int]):
        Only port pages from these namespace IDs.
      include_pageids (List[int]):
        Only port pages with these page IDs.
      exclude_namespaces (List[int]):
        Do not port pages from these namespace IDs.
      exclude_pageids (List[int]):
        Do not port pages with these page IDs.
      export ("only_non_redirects" | "only_redirects" | "all"):
        Port redirects/do not port/port all pages.  
  """
  db_conn = sqlite3.connect(sql_db_path)
  db_cursor = db_conn.cursor()

  filter_kwargs = {
    "include_namespaces": include_namespaces,
    "exclude_namespaces": exclude_namespaces,
    "include_pageids": include_pageids,
    "exclude_pageids": exclude_pageids,
    "export": export,
  }
  query = generate_sql_query(for_count=True, **filter_kwargs)
  logger.info(f"Executing query: {query}")
  num_items = db_cursor.execute(query).fetchone()[0]
  logger.info(f"Found {num_items} item(s)")

  num_text_files = num_items // num_pages_per_file
  if (num_items % num_pages_per_file > 0):
    num_text_files += 1

  offset = 0
  for i in range(num_text_files):
    filename = f"{exported_filename_prefix}{i+1}.xml"
    filepath = f"{re.sub(r"\/$", "", output_directory)}/{filename}"

    with open(filepath, 'w', encoding='UTF-8') as f:
      # Writes the root <mediawiki> element that contains XML definitions
      f.write(root_xml_head)
      # Writes the <siteinfo> element that contains the wiki's namespace information
      f.write(siteinfo_xml)
      
      # Write in batches
      for _ in range(num_pages_per_file // num_items_to_fetch_from_db):
        query = generate_sql_query(
          for_count=False, 
          limit=num_items_to_fetch_from_db, 
          offset=offset,
          **filter_kwargs
        )
        logger.info(f"Executing query: {query}")
        items = db_cursor.execute(query).fetchall()
        if len(items) == 0:
          break
        offset += len(items)
        [f.write(contents) for _, contents in items]
      
      # Close the root element
      f.write("</mediawiki>\n")
    
    logger.info(f"Finished writing {filename}")

  db_conn.close()


def generate_sql_query(
    for_count: bool, 
    limit: int = 0, 
    offset: int = 0, 
    include_namespaces: List[int] = [],
    include_pageids: List[int] = [],
    exclude_namespaces: List[int] = [],
    exclude_pageids: List[int] = [],
    export: Literal["only_non_redirects", "only_redirects", "all"] = "all"
  ) -> str:
  query = f"SELECT {"COUNT(w.id)" if for_count else "w.id, w.contents"} FROM WikipageContentXmls w"
  where_clauses = []
  if len(include_namespaces) > 0:
    where_clauses.append(f"w.ns IN ({','.join(map(lambda x: str(x), include_namespaces))})")
  if len(exclude_namespaces) > 0:
    where_clauses.append(f"w.ns NOT IN ({','.join(map(lambda x: str(x), exclude_namespaces))})")
  if len(include_pageids) > 0:
    where_clauses.append(f"w.id IN ({','.join(map(lambda x: str(x), include_pageids))})")
  if len(exclude_pageids) > 0:
    where_clauses.append(f"w.id NOT IN ({','.join(map(lambda x: str(x), exclude_pageids))})")
  if export == "only_non_redirects":
    where_clauses.append(f"w.redirect_to IS NULL")
  elif export == "only_redirects":
    where_clauses.append(f"w.redirect_to IS NOT NULL")
  
  if len(where_clauses) > 0:
    query += " WHERE " + " AND ".join(where_clauses)
  
  if not for_count:
    query += f" LIMIT {limit} OFFSET {offset}"

  query += ";"

  return query